// @ts-check
const docs_api = {
  type: "category",
  label: 'MonoGame.Aseprite',
  collapsible: false,
  collapsed: false,
  items: [
    {
      type: "autogenerated",
      dirName: 'api/MonoGame.Aseprite'
    }
  ]
}

const sidebars = {
  docsSidebar: [
    {
      type: "category",
      label: "MonoGame.Aseprite",
      items: ["introduction"],
    },
    {
      type: "category",
      label: "Getting Started",
      items: ["getting-started/installation", "getting-started/setup-mgcb-editor", "getting-started/load-aseprite-file/load-aseprite-file"],
    },
    {
      type: "category",
      label: "Processors",
      items: [
        "processors/processors-overview",
        "processors/sprite-processor",
        "processors/texture-atlas-processor",
        "processors/sprite-sheet-processor",
        "processors/tileset-processor",
        "processors/tilemap-processor",
        "processors/animated-tilemap-processor",
      ],
    },
  ],
  apiSidebar: [
    docs_api
  ]
};

module.exports = sidebars;
