name: Main
on:
    push:
        branches:
            - 'main'
    pull_request:
        branches:
            - 'main'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repository
              uses: actions/checkout@v2
              with:
                submodules: recursive
            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
            - name: Restore dotnet tools
              run: dotnet tool restore
            - name: Run Build
              run: donet docfx ./build/docfx.json
            - name: Upload To Server
              run: |
                echo ${{ secrets.SSH_PRIVATE_KEY }} >> ~/.ssh/key
                rsync -avh -e  "ssh -i ~/.ssh/key" --progress /artifacts/_site/* ${{ secrets.REMOTE_USER}}@${{ secrets.REMOTE_HOST}}:${{ secrets.REMOTE_TARGET }}
              
              


