on: push
name: Publish Website
jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "npm"
      run: npm ci

    - name: Build Project
      run: |
        npm ci
        npm run build
    
    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: ${{ secrets.SSH_DOMAIN }}
        remote-user: ${{ secrets.SSH_USER }}
        private-ssh-key: ${{ secrets.SSH_KEY }}
        destination-path: ${{ secrets.DESTINATION_PATH }}
        source-path: ${{ secrets.SOURCE_PATH }}